001 File %s not found.
002 Error reading file %s.
003 File %s contains no data.
004 Error opening log file %s

006 Not enough memory
007 Batch name missed.

009 Too many nested packages (%d)
010 Package %s recursively imported
011 Incorrect package name %s
012 Import (%s,%d,%d): %s.
013 Part ³ %s.
014 Imported package %s not found.
016 No RETURN statement in imported package %s
017 Jump on error %d.
018 Unknown directive %s
019 Error writing protocol file.


100 Package %s is being executed
101 Package %s execution %s.
102 interrupted
103 finished
104 Warning (%s,%d,%d): %s.
105 Error %d (%s,%d,%d): %s.
106 Total errors %d, warnings %d.
107 Parameter expected
108 Extra parameters ignored
109 %5d³%s

111 Label '%s' already defined
112 Incorrect label
113 Label matches reserved word
114 Label not found
115 RETURN without CALL
116 Program not loaded
117 Incorrect log file name
118 Statement expected
119 Nested variants are not allowed
120 -----³ Begin variant %s
121 -----³ End variant %s
122 END VARIANT without BEGIN VARIANT
123 Execution time %d ticks.
124 Pause. Press any key to continue...
125 Pause %d sec. Press any key to continue...
126 Incorrect parameter
127 Incorrect program name
128 THEN expected
129 Program start not allowed
130 Program was not started
131 Incorrect address

133 Program can't restarted
134 Expression expected
135 Restart not allowed
136 Comma expected
137 Incorrect mode
138 Errors limit set to %d

140 Error in table (%s,%d,%d) %s.
141      ³ %$8X %s
142 Address %$8X: %s.
143 Double quotes expected
144 String not terminated (double quotes expected)
145 Break '%s', address %$8X: %s.
146 Exception '%s' at %$8X
147 Write in [%$8X..%$8X] by address %$8X\nblock length %u, old value 0%sH, new value 0%sH
148 Breakpoint
149 Condition %s
150 Line %d in module %s
151 Program finished
152 Breakpoint identifier already in use
153 Incorrect event identifier
154 Assert
155 Incorrect length
156 Variable expected
157 Address value expected
158 Incorrect line number; will be used %i line number
159 Line number expected
160 Incorrect line number
161 Break already exists
162 Break identifier '%s' not found
163 Incorrect alias
164 Alias %s not defined
165 Program name expected

168 Label expected
169 Breakpoint identifier expected
170 Breakpoint type expected
171 Breakpoint attributes expected
172 Mode expected
173 Variant name expected
174 Alias expected
175 Alias definiton expected
176 Incorrect expression

182 Incorrect break
183 Expression result not defined (some names are out of scope)
184 Write in register %s, length %u\nold value X'%s', new value X'%s'
185 Incorrect file name

187 Write to register %s failed
188 Read from register %s failed
189 Alias type expected
190 Read/Write memory access, address %$8X\nblock len = %u, read value 0x%s
191 Read from register %s\nlength %u, register value 0x%s
192 Procedure call
193 Procedure call on address %$8X
194 Return from procedure, address %$8X
195 Component %s loaded
196 Address 0x%$8X is out of space
197 Write to ROM, address %$8X
198 Call device %s.%s (status %s, exchange address %$8X), length %u
199 Component %s is about to be unloaded

200 Variable or register expected
201 Type incompatibility in assignment
203 Write to address %$8X failed, len %d
204 Read from address %$8X failed, len %d
205 Stuctured variable not allowed in this context
206 Register is not allowed
207 Overlapped blocks at: %$8X %$8X
208 Error code expected
209 Incorrect error list action
210 Incorrect error code
211 Handler for error %d already defined
212 Handler for error %d not defined
213 Module not found

215 Specified length (%u) exceeds length of constant (%u)
216 Keyword can not be redefined

219 Search string not found
220 Boolean value expected

313 Ctrl-Break pressed

600 Types incompatible
601 Division by zero
602 Incorrect operation usage
603 Real constant out of range
604 Incomplete whole constant
605 Illegal whole constant
606 Illegal real constant
608 Value out of range
609 Unknown special name

611 Incorrect token in expression
612 Unknown type
613 Object is not array
614 Incompatible index type
615 Out of range
616 Period expected
617 Identifier expected
618 Recursive alias usage
619 Object not found
620 Whole value expected
621 Incorrect factor
622 Empty expression
623 Incorrect expression
624 Whole value expected

627 Address or register expected

629 Memory access failed
630 Object is not record
631 Record field expected
632 Address is out of address space
633 Invalid array descriptor

700 Loading %s: %s
716 There is no debug info in program\nor wrong format of debug info
719 Program not found
725 Executable file and debug information inconsistent

732 Wrong program information 
733 Wrong version debug info or\nnot found Dll-reader for this version
734 Program already started
735 Program not found
736 Cannot create process
737 Invalid program header

740 Instruction pointer is out of known executable segments.\n          Further execution is unpredictable.

801 Classes
802 Module globals
803 Modules
804 Call Stack
805 Watches
806 Breaks
807 Segments for module %s
808 Registers
809 Dump: %$8X
810 Stack
811 Colors
812 Color schemes
813 Options
814 Registers of device %s
815 Devices
816 Variable
817 Error
818 Warning
819 Input new value
820 Enter line number
822 Enter watch
823 Program name
824 Enter Variable
825 Enter address
826 Enter delay pass number
827 Enter breakpoint condition
829 Procedures
830 Labels
831 Methods
832 Functions
833 Module types
834 Enter alias for type
835 Aliases

839 Message
840 | Counter: %d
841 | Condition: %s
842 | Pass Left: %d
843 Locals
844 Parameters
845 Globals

850 You must enter the condition
851 Condition hits\n%s
852 Error in config file %s, line %u
853 Error in keyboard settings file %s, line %u
854 Line number is out of module bounds
855 About

900 Address is out of executable segment bounds
901 Help: Contents
902 Help: %s
903 Help-file not found
904 Invalid value for option '%s'
905 %$8X  %s
906 ÚÄ Enter expression ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
907 Enter string to search
908 Read/Write access at %$8X..%$8X
909 Read from register %s
910 Write access at %$8X..%$8X
911 Write to register %s
912 Condition: %s
913 Dump write protected
914 Stack: SP+%X
915 Enter address
916 Enter condition to stop
917 This break is now set but have disabled state\ndue to hardware limit of access breaks.\nYou can enable it later if place will be free
918 Wrong expression in current context:\n%s
919 Component %s is about to be unloaded.\nAll breakpoints set in it will now be disabled.
920 RTS exception #%u: %s
921 Exception has been raised while running to main entry

951 Host unknown
952 Wrong socket
953 Connection not established
954 Wrong identification
955 Connection already established
956 Over max pending connects
957 Wrong connection
958 Unknown transport
959 Wrong initialization transport
960 DLL transport not found
961 Wrong format DLL transport
962 Something error remote debugging

999 IF THIS MESSAGE DISPLAYED\nSOME INTERNAL DEBUGGER ERROR DETECTED!
