/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef Krn_Prog_H_
#define Krn_Prog_H_
#ifndef X2C_H_
#include "X2C.h"
#endif
#ifndef KrnTypes_H_
#include "KrnTypes.h"
#endif

extern X2C_CARD32 Krn_Prog_StartProgram(X2C_CHAR [], X2C_CARD32, X2C_CHAR [], X2C_CARD32);

extern X2C_BOOLEAN Krn_Prog_GetProgramInfo(struct KrnTypes_EXEC_INFO *);

extern X2C_BOOLEAN Krn_Prog_GetDebugInfo(struct KrnTypes_EXEC_INFO, X2C_ADDRESS);

enum Krn_Prog_MODE {Krn_Prog_None, 
   Krn_Prog_SingleStep, 
   Krn_Prog_RangeStep, 
   Krn_Prog_Go};


struct Krn_Prog_GO_MODE;


struct Krn_Prog_GO_MODE {
   X2C_CARD8 mode;
   union {
      struct {
         X2C_CARD32 Begin;
         X2C_CARD32 End;
      } _0;
      X2C_BOOLEAN add_step;
   } __attribute((aligned(1), packed)) _;
} __attribute((aligned(1), packed));

extern X2C_BOOLEAN Krn_Prog_ProgramExecuting;

extern void Krn_Prog_Execute(struct Krn_Prog_GO_MODE);

extern X2C_BOOLEAN Krn_Prog_ReadExport(X2C_CHAR [], X2C_CARD32, KrnTypes_EXPORTS *);

extern X2C_BOOLEAN Krn_Prog_RestartProgram(void);

extern void Krn_Prog_UnloadProgram(void);


extern void Krn_Prog_BEGIN(void);


#endif /* Krn_Prog_H_ */
