/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#ifndef KrnTypes_H_
#define KrnTypes_H_
#ifndef X2C_H_
#include "X2C.h"
#endif

#define KrnTypes_prg_file_ext ""

#define KrnTypes_ref_file_ext ""

#define KrnTypes_pkt_file_ext "XD"

#define KrnTypes_imp_file_ext "XD"

#define KrnTypes_res_file_ext "XDL"

#define KrnTypes_dll_file_ext ""

#define KrnTypes_tbl_file_ext "TDD"

typedef X2C_CHAR KrnTypes_PROGRAM_NAME[256];

enum KrnTypes_APP_TYPE {KrnTypes_none, KrnTypes_console, KrnTypes_windowed};


enum KrnTypes_ATTRIB {KrnTypes_execute, KrnTypes_read, KrnTypes_write, KrnTypes_bit_32};


typedef X2C_CARD8 KrnTypes_ATTRIBS;

struct KrnTypes_OBJECT;


struct KrnTypes_OBJECT {
   X2C_CARD8 Attributes;
   X2C_CARD32 RelocationBase;
   X2C_CARD32 Begin;
   X2C_CARD32 End;
} __attribute((aligned(1), packed));

struct KrnTypes_EXEC_INFO;


struct KrnTypes__D0 {
   struct KrnTypes_OBJECT * Adr;
   X2C_INDEX Len0;
} __attribute((aligned(1), packed));


struct KrnTypes_EXEC_INFO {
   KrnTypes_PROGRAM_NAME short_name;
   KrnTypes_PROGRAM_NAME full_name;
   X2C_CARD8 app_type;
   X2C_CARD32 Handle;
   X2C_CARD32 hFile;
   X2C_CARD32 StartupEntry;
   X2C_CARD32 MainEntry;
   X2C_CHAR DebugInfoTag[5];
   X2C_CARD32 DebugInfoStart;
   X2C_CARD32 DebugInfoSize;
   X2C_CARD32 N_Objects;
   struct KrnTypes__D0 * Objects;
   X2C_CARD32 Code_Object;
} __attribute((aligned(1), packed));

extern struct KrnTypes_EXEC_INFO KrnTypes_EmptyExecInfo;

typedef X2C_CARD32 KrnTypes_ADDRESS;

typedef X2C_WORD KrnTypes_WORD;

#define KrnTypes_NIL_ADDRESS 0

#define KrnTypes_SIZE_ADDRESS 4

#define KrnTypes_RegsNum 32

#define KrnTypes_ShownRegs 10

#define KrnTypes_UserRegs 8

#define KrnTypes_FloatRegs 8

typedef X2C_CARD32 KrnTypes_REG_VALUE;

typedef X2C_CHAR KrnTypes_REG_NAME[7];

struct KrnTypes_REGISTER;


struct KrnTypes_REGISTER {
   KrnTypes_REG_NAME name;
   X2C_CARD32 reg_no;
} __attribute((aligned(1), packed));

typedef struct KrnTypes_REGISTER KrnTypes_REGISTERS[32];

//typedef X2C_LONGDOUBLE KrnTypes_REGISTER_DATA[8];
typedef X2C_CHAR KrnTypes_REGISTER_DATA[80];

struct KrnTypes_FLOATING_REGISTER_CAC;


struct KrnTypes_FLOATING_REGISTER_CAC {
   X2C_CARD32 ControlWord;
   X2C_CARD32 StatusWord;
   X2C_CARD32 TagWord;
   X2C_CARD32 ErrorOffset;
   X2C_CARD32 ErrorSelector;
   X2C_CARD32 DataOffset;
   X2C_CARD32 DataSelector;
   KrnTypes_REGISTER_DATA RegisterData;
   X2C_CARD32 Cr0NpxState;
} __attribute((aligned(1), packed));

struct KrnTypes_REGISTER_CACHE;

union KrnTypes__D1;


union KrnTypes__D1 {
   X2C_CARD32 dw;
   X2C_CARD16 w;
   struct {
      X2C_CARD8 l;
      X2C_CARD8 h;
   }  __attribute((aligned(1), packed));
} __attribute((aligned(1), packed));


struct KrnTypes_REGISTER_CACHE {
   struct KrnTypes_FLOATING_REGISTER_CAC FloatingRegisters;
   union {
      struct {
         X2C_CARD32 Eax;
         X2C_CARD32 Ecx;
         X2C_CARD32 Edx;
         X2C_CARD32 Ebx;
         X2C_CARD32 Esp;
         X2C_CARD32 Ebp;
         X2C_CARD32 Esi;
         X2C_CARD32 Edi;
         X2C_CARD16 SegEs;
         X2C_CARD16 SegCs;
         X2C_CARD16 SegSs;
         X2C_CARD16 SegDs;
         X2C_CARD16 SegFs;
         X2C_CARD16 SegGs;
         X2C_CARD32 BaseEs;
         X2C_CARD32 BaseCs;
         X2C_CARD32 BaseSs;
         X2C_CARD32 BaseDs;
         X2C_CARD32 BaseFs;
         X2C_CARD32 BaseGs;
      } __attribute((aligned(1), packed)) _0;
      struct {
         union KrnTypes__D1 Common[8];
         X2C_CARD16 Segs[6];
         X2C_CARD32 Bases[6];
      } __attribute((aligned(1), packed)) _1;
   } __attribute((aligned(1), packed)) _;
   X2C_CARD32 Eip;
   X2C_CARD32 EFlags;
} __attribute((aligned(1), packed));

struct KrnTypes_FLAGS;


struct KrnTypes_FLAGS {
   X2C_BOOLEAN O;
   X2C_BOOLEAN D;
   X2C_BOOLEAN S;
   X2C_BOOLEAN Z;
   X2C_BOOLEAN A;
   X2C_BOOLEAN P;
   X2C_BOOLEAN C;
} __attribute((aligned(1), packed));

#define KrnTypes_EIP 0x22 

#define KrnTypes_EFL 0x24 

#define KrnTypes_ESP 0x14 

#define KrnTypes_FRAME_REG 0x15 

extern KrnTypes_REGISTERS KrnTypes_Registers0;

#define KrnTypes_BreakLen 1

typedef X2C_CARD8 KrnTypes_BREAK_CODE[1];

extern KrnTypes_BREAK_CODE KrnTypes_CodeBreakInterrupt;

typedef X2C_CHAR KrnTypes_ENTRY_NAME[256];

struct KrnTypes_EXPORTED;


struct KrnTypes_EXPORTED {
   X2C_CARD32 obj;
   X2C_CARD32 offset;
   KrnTypes_ENTRY_NAME name;
} __attribute((aligned(1), packed));


struct KrnTypes__D2 {
   struct KrnTypes_EXPORTED * Adr;
   X2C_INDEX Len0;
} __attribute((aligned(1), packed));

typedef struct KrnTypes__D2 * KrnTypes_EXPORTS;


extern void KrnTypes_BEGIN(void);


#endif /* KrnTypes_H_ */
